name: Run recursion Tests on PR
on:
  pull_request:
    paths:
      - "recursion/**"

jobs:
  test:
    defaults:
      run:
        working-directory: recursion

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: stable

      - name: Install bb
        run: |
          curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/master/barretenberg/bbup/install | bash
          echo "PATH=$PATH:/home/runner/.bb" >> $GITHUB_ENV

      - name: Run bbup
        run: |
          bbup

      - name: Build circuits
        run: |
          ./build.sh
        working-directory: recursion/circuits

      - name: Install JS dependencies
        working-directory: recursion/js
        run: |
          yarn install

      - name: Generate proof in JS
        run: |
          yarn generate-proof
        working-directory: recursion/js
